# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-05-18 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210517_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户表'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='/img/default.jpg', upload_to='static'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='手机号'),
        ),
    ]
