# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-05-25 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210518_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views_num',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='user',
            name='blog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.BlogSite'),
        ),
    ]
